### ISSUE TITLE
Missing link to resend confirmation email while changing password

### ISSUE THREAD

**Issue by dkanevskiy** [strongqa/demo_web_app#1]
Steps to reproduce:
1. Open Login page: http://demoapp.strongqa.com/users/sign_in
2. Click on 'Forgot password' link.
3. Fill Email form on Reset password page.
4. Confirm Email form.
ER: On Login page i should see link to resend confirmation email (e.g 'Didn't receive confirmation instructions?').
AR: Link to resend confirmation email is absent on Login page.
Please see: http://prntscr.com/6wt4zd

**Comment by romikoops** [comment]
Please retest due to the issue is old

**Comment by greenhairedlime** [comment]
The issue is still reproducible. I don't see any resend link, but I suppose it is not expected.

**Comment by romikoops** [comment]
I retested it and it works. I receive email notification with password update link
