### ISSUE TITLE
Missing link to resend confirmation email while changing email

### ISSUE THREAD

**Issue by dkanevskiy** [strongqa/demo_web_app#2]
Steps to reproduce:
1. Login to the system.
2. Open Edit account page.
3. Edit email form (specify an existent email).
4. Fill Current password field.
5. Confirm Edit user form.
ER: On Home page i should see link to resend confirmation email (e.g 'Didn't receive confirmation instructions?')
AR: Link to resend confirmation email is absent on Home page.
Please see http://prntscr.com/6wt81g

**Comment by romikoops** [comment]
The issue is old, please retest

**Comment by greenhairedlime** [comment]
Updated issue steps to reproduce:
1. Login to the system
2. Go to Users
3. Click `Edit Account` button
4. Fill new existing email to the email field in.
5. Fill current password in.
6. Confirm email update by clicking Update button

*AR:* There is only floating notification about email confirmation, but there is no resend confirmation email link
*ER:*  Somewhere should be a link to resend confirmation email (e.g 'Didn't receive confirmation instructions?')

**Comment by romikoops** [comment]
link is not provided on website due to security reason. I receive the email normally. 
I have reviewed mailgun account and see it was used corporate email as a new email. Zoho server was rejected it cause of special spam filtering rules.
