### ISSUE TITLE
Error during Login on demoapp.strongqa.com

### ISSUE THREAD

**Issue by evgeniyvlb** [strongqa/demo_web_app#28]
1, Open https://demoapp.strongqa.com/users/sign_in page
2. Enter credentials and click "Log in" button

[AR] Error appears
> We're sorry, but something went wrong. 
> If you are the application owner check the logs for more information.

**Comment by Lec1k** [comment]
@evgeniyvlb error should be fixed for now, please reopen this issue if you face it again
